allowBuilds:
  esbuild: true
  sharp: true

engineStrict: true

gitBranchLockfile: true

mergeGitBranchLockfilesBranchPattern:
  - main
  - release*

overrides:
  "vite": "^8.0.0"

shellEmulator: true

verifyDepsBeforeRun: install
